### ISSUE TITLE
从互联网档案馆恢复共识网

### ISSUE THREAD

**Issue by NodeBE4** [co-memory/bbs#3]
[维基百科](https://zh.wikipedia.org/wiki/%E5%85%B1%E8%AF%86%E7%BD%91)

> 共识网（Consensus Net[3]；Consensus Web[4]）是香港《领导者》杂志旗下的简体字官方网站[5]，是一个于2009年2月20日由立德共识（北京）网络传媒科技有限公司创立的学术、思想性网站，内容涵盖政治、历史和经济题材，既有知名自由派学者，也有左派学者文章，网站宗旨为“在大变革时代寻找共识”。
> 
> 共识网于2009年7月1日正式接入国际互联网[6]，栏目包括“全球事务”、中国研究、“历史解读”以及“思想评论”等。共识网创办人周志兴[7]在2016年10月3日称，中国当局认为共识网是传递错误思想的平台，勒令关闭共识网[8][注 1]
> 

https://web.archive.org/web/20101104043003/http://www.21ccom.net/

@PincongBot @duty-machine @lestweforget

**Comment by lestweforget** [comment]
手工恢复的话工作量很大，但应该会有更好的办法？

**Comment by NodeBE4** [comment]
> 手工恢复的话工作量很大，但应该会有更好的办法？

肯定要用代码恢复的

**Comment by NodeBE4** [comment]
https://nodebe4.github.io/21ccom/
